version: '3'

services:
  node-app:
    build: .
    image: node-app
    environment:
    #   - MONGODB_URL=mongodb://mongodb:27017/node-boilerplate
      - MONGODB_URL=mongodb+srv://investor-checklist-tool-backend:CaLIU1HR1wnE9ZJ9@cluster0.ru8xaxp.mongodb.net/ice-t?retryWrites=true
      # - HUSKY_SKIP_INSTALL=1
    ports:
      - '3000:3000'
    # depends_on:
    #   - mongodb
    volumes:
      - .:/usr/src/node-app
    networks:
      - node-network

  # below is for mongodb instance on the same docker network as node-app above
  # mongodb:
  #   image: mongo:4.2.1-bionic
  #   ports:
  #     - '27017:27017'
  #   volumes:
  #     - dbdata:/data/db
  #   networks:
  #     - node-network

# volumes:
#   dbdata:

networks:
  node-network:
    driver: bridge
